name: Showcase Submission
description: Submit your resource pack to the showcase
labels: ['showcase']
body:
  - type: input
    id: project_name
    attributes:
      label: Project Name
    validations:
      required: true

  - type: input
    id: modrinth_id
    attributes:
      label: Modrinth Project ID

  - type: input
    id: curseforge_id
    attributes:
      label: CurseForge Project ID

  - type: textarea
    id: notes
    attributes:
      label: Notes

  - type: markdown
    attributes:
      value: '<br />'

  - type: markdown
    attributes:
      value: '## Static data'

  - type: markdown
    attributes: 
      value: This is not required if you already entered a valid Modrinth or CurseForge ID, otherwise you must fill out everything below.

  - type: input
    attributes:
      label: Author
  
  - type: input
    attributes:
      label: Icon URL

  - type: input
    attributes: 
      label: Short Description

  - type: textarea
    attributes:
      label: External Links
      description: 'Enter any number of external links. Must have at least one if there is no Modrinth or CurseForge ID.'
      placeholder: 'PlanetMinecraft - https://www.planetminecraft.com/texture-pack/bedrock-style-cursors-for-java-edition/'
       